name: Update Data

on:
  workflow_dispatch:
  schedule:
    # Run every hour, five minutes after the hour
    - cron: '0 * * * *'

jobs:
  run-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      - name: Execute update notebook
        run: |
          jupyter nbconvert --to notebook --execute data/update.ipynb --output data/update.ipynb

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Automated data update'
          branch: data-refresh
          title: 'Automated data update'
          body: 'This PR contains results from running `data/update.ipynb`.'
