name: Update Data

on:
  workflow_dispatch:
  schedule:
    # Run every hour, five minutes after the hour
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  run-update:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      - name: Execute update notebook
        run: |
          jupyter nbconvert --to notebook --execute update.ipynb --output update.ipynb --output-dir ./

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Automated data update'
          branch: data-refresh
          title: 'Automated data update'
          body: 'This PR contains results from running `update.ipynb`.'
          delete-branch: true
          merge: true
          merge-method: squash

      - name: Force merge pull request
        if: steps.cpr.outputs.pull-request-number != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number(process.env.PR_NUMBER),
              merge_method: 'squash'
            })
        env:
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
